### ISSUE TITLE
error: unknown option `--print-config' in a new nestjs project

### ISSUE THREAD

**Issue by itays** [JoshuaKGoldberg/tslint-to-eslint-config#106]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 0.1.9
-   ESLint version: 6.0.1
-   Node version: 12.4.0

#### Actual Behavior

currently nestjs framework still ships with tslint. I created a new nestjs project and run `npx tslint-to-eslint-config` and got: 

Could not start tslint-to-eslint: 
Command failed: tslint --print-config "./tslint.json"
error: unknown option `--print-config'

#### Expected Behavior

eslint json file should be created

#### Reproduction
install the nestjs cli tool:
`npm i -g @nestjs/cli`
create a nestjs project:
`nest new project-name`
cd into the newly created project and run `npx tslint-to-eslint-config`

**Comment by JoshuaKGoldberg** [comment]
👋 Thanks for the bug report @itays! If you update your TSLint version to `5.18.0`, the issue will go away.

The problem is that TSLint added the `--print-config` flag only recently, and `tslint-to-eslint-config` relies on it. I'll send a PR to add an explicit dependency to this package on sufficient `tslint` and `typescript` versions.

**Comment by JoshuaKGoldberg** [comment]
This should be fixed in `0.2.0`:

```shell
npx tslint-to-eslint-config@0.2
```

Please do post here if that doesn't fix this bug for you! 🚀

**Comment by JoshuaKGoldberg** [comment]
FYI: as of `0.2.2`, the error message when the TSLint version is too low will explicitly indicate it should be updated.

```
❌ Could not start tslint-to-eslint: ❌
TSLint v5.18 required. Please update your version.
```

**Comment by Yavorss** [comment]
@JoshuaKGoldberg Do I need exactly 5.18v?

![image](https://user-images.githubusercontent.com/16567086/69197130-45c80800-0b39-11ea-9d4c-3fb5b7893a4f.png)

**Comment by Yavorss** [comment]
@JoshuaKGoldberg  Do I need exactly 5.18v?

![image](https://user-images.githubusercontent.com/16567086/69197196-727c1f80-0b39-11ea-8fb0-ae2bf1493c2e.png)

**Comment by JoshuaKGoldberg** [comment]
Oh interesting. You should be able to use `5.20.1`, and generally anything >=5.18. Would you mind filing a new issue with your version?

**Comment by bephrem1** [comment]
Oddly still getting this in a NextJS project where we use `TSLint`:
```
bephrem in web (⍒ master)$ npx tslint-to-eslint-config    
npx: installed 60 in 6.359s
❌ Could not start tslint-to-eslint: ❌
  Command failed: tslint --print-config "./tslint.json"
Failed to load /Users/bephrem/Documents/Social Checkout/sc-web/tslint.json: Cannot read property 'func' of undefined
```

**Comment by bephrem1** [comment]
Ah, it was:
```
"extends": ["tslint-react", "tslint-config-prettier", **"react-hooks"**],
```

This never resolved, I don't even remember if that ever resolved to anything. Removed and works.
